FROM node:18-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
ENV NEXT_PUBLIC_API_URL=http://192.168.12.6:8087
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
